#' Combines any split tables back into one table
#' @description  For a given data dictionary table this function will combine any
#' tables that were previously split, using the split_lookups
#' @param dictionary_tables a list of data.frames where each element corresponds
#' to a specific data dictionary table
#' @param split_lookups list of split lookup values generated by `get_all_split_keys`
#' which will be split
#' @return a list of dictionary tables
combine_split_tables <- function(dictionary_tables, split_lookups){

    combined_dfs = vector("list", length(split_lookups))

    to_remove_from_dict = vector("list", length(split_lookups))

    for (table in seq_along(split_lookups)) {

        tbls_to_recombine = names(split_lookups[[table]][["customer"]])

        combined_dfs[[table]] = dplyr::bind_rows(dictionary_tables[tbls_to_recombine])

        names(combined_dfs)[[table]] = split_lookups[[table]][["dd_split_tbl"]]


        to_remove_from_dict[[table]] = tbls_to_recombine

        tbl_print_name = unlist(
            stringr::str_split(split_lookups[[table]][["dd_split_tbl"]], pattern = "_")
        )

        if(length(tbl_print_name) == 1){
            tbl_print_name = toupper(tbl_print_name)
        } else tbl_print_name = tools::toTitleCase(tbl_print_name)

        tbl_print_name =  paste0(tbl_print_name, collapse = " ")

        cli::cat_line(cli::col_yellow(cli::symbol$info),
                      cli::col_grey(" Re-combined "),
                      cli::col_grey({length(tbls_to_recombine)}),
                      cli::col_grey(" "),
                      cli::col_grey({tbl_print_name}),
                      cli::col_grey(" tables"))
    }

    dict_keep = !names(dictionary_tables) %in% unlist(to_remove_from_dict)

    return(c(dictionary_tables[dict_keep], combined_dfs))

}
