#' Split a data dictionary table based on the fields within a customer table
#' @description  For a given data dictionary table this function will split the table
#' based the common values found within a user-defined field
#' @param dictionary_tables a list of data.frames where each element corresponds
#' to a specific data dictionary table
#' @param split_field the name of the field that will be used to create the split tables
#' @param split_lookups list of split lookup values generated by `get_all_split_keys`
#' which will be split
#' @return a list of split data.frames
create_split_table = function(dictionary_tables,
                              split_lookups,
                              split_field = "display_name"){

    lookups = split_lookups[["customer"]]
    table_to_split = split_lookups[["dd_split_tbl"]]

    split_dfs = vector("list", length(lookups))

    for (lookup in seq_along(lookups)) {

        split_dfs[[lookup]] = dictionary_tables[[table_to_split]]

        split_dfs[[lookup]][[split_field]] = tolower(split_dfs[[lookup]][[split_field]])

        filter_index = split_dfs[[lookup]][[split_field]] %in% tolower(lookups[[lookup]])

        split_dfs[[lookup]] = split_dfs[[lookup]][filter_index,]

        names(split_dfs)[[lookup]] = names(lookups)[[lookup]]

        }

    return(split_dfs)

}



#' Split a data dictionary table based on the fields within a customer table
#' @description  For a given data dictionary table this function will split the table
#' based the common values found within a user-defined field
#' @param dictionary_tables a list of data.frames where each element corresponds
#' to a specific data dictionary table
#' @param split_field the name of the field that will be used to create the split tables
#' @param split_lookups list of split lookup values generated by `get_all_split_keys`
#' which will be split
#' @return a list of dictionary tables including the split data.frame tables
split_tables = function(dictionary_tables, split_lookups,
                        split_field = "display_name"){

    split_dfs = vector("list", length(split_lookups))


    for (dataset in seq_along(split_lookups)) {

        split_dfs[[dataset]] =  create_split_table(
            dictionary_tables = dictionary_tables,
            split_lookups = split_lookups[[dataset]],
            split_field = split_field)

        tbl_print_name = unlist(
            stringr::str_split(split_lookups[[dataset]][["dd_split_tbl"]], pattern = "_")
            )

        if(length(tbl_print_name) == 1){
            tbl_print_name = toupper(tbl_print_name)
        } else tbl_print_name = tools::toTitleCase(tbl_print_name)

        tbl_print_name =  paste0(tbl_print_name, collapse = " ")

        cli::cat_line(cli::col_yellow(cli::symbol$info),
                      cli::col_grey(" Split "),
                      cli::col_grey({tbl_print_name}),
                      cli::col_grey(" into "),
                      cli::col_grey({length(split_dfs[[dataset]])}),
                      cli::col_grey(" tables"))
    }

    split_dfs = purrr::flatten(split_dfs)

    return(c(dictionary_tables, split_dfs))

}

